### PR TITLE
Fix fimg noblob (#90)

### LINKED ISSUE #90: FindImage with blob=False crashes server
FindImage with blob=False crashes server

Server error:
```
"vdms: src/ImageCommand.cc:238: virtual Json::Value VDMS::FindImage::construct_responses(Json::Value&, const Json::Value&, VDMS::protobufs::queryMessage&, const string&): Assertion `findImage.isMember(""entities"")' failed.
/start.sh: line 5:    13 Aborted                 (core dumped) ./vdms
```

### PR DESCRIPTION
**Pull request by luisremis**
Fix #90

### CODE REVIEW

**Comment by luisremis** [comment]
@vishakha041, git gets confused on the changes on ImageCommand.cc. I recommend you look at the files directly to see the changes (that are way less complicated than what it appears)

File: src/ImageCommand.cc [hunk 1]
```diff
@@ -235,85 +235,90 @@ Json::Value FindImage::construct_responses(
...
-    assert(findImage.isMember("entities"));
-
     if (findImage["status"] != 0) {
         findImage["status"]  = RSCommand::Error;
         // Uses PMGD info error.
         return error(findImage);
     }
 
-    bool flag_empty = true;
+    Json::Value results = get_value<Json::Value>(cmd, "results");
```
Comment (vishakha041) [inline src/ImageCommand.cc]: Actually I am quite confused with this commit. Shouldn't we check in construct_protobuf if blob == false and no list/count/average requested? Or is this relying on PMGDQueryHandler throwing an error and then handling it construct_responses? Ideally we should put it in JSON checks but I am guessing that's not possible. What am I missing?
